version: "3"
services:
  backend:
    build: ./backend
    container_name: backend_app
    ports:
      - "4000:4000"
    networks:
      - my-network
  frontend:
    build: ./frontend
    container_name: frontend_app
    ports:
      - "8000:8000"
    depends_on:
      - backend
    networks:
      - my-network

networks:
  my-network:
